[package]
name = "soundmaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
cpal = "0.15.3"
fundsp = "0.16.0"
petgraph = "0.6.4"
piston_window = "0.131.0"
typenum = "1.17.0"
